version: '3.8'

services:
  api:
    build: .
    container_name: falatu-api
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
    ports:
      - "3333:3333"
      - "80:80"
      - "81:81"
    networks:
      - falatu-backend

  postgres:
    image: postgres:latest
    container_name: falatu-db
    volumes:
      - ./containers/database/postgres/volumes:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    expose:
      - 5432
    networks:
      - falatu-backend

networks:
  falatu-backend:
    driver: bridge
